global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "monitoring-app"
    scrape_interval: 5s
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/metrics"

  # Add additional targets for monitoring
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Example: Azure services (via Azure exporter)
  # - job_name: 'azure-exporter'
  #   static_configs:
  #     - targets: ['azure-exporter:9276'] 