apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    
  - name: Google Cloud Monitoring
    type: grafana-googlecloud-datasource
    access: proxy
    jsonData:
      authenticationType: jwt
      clientEmail: $GCP_CLIENT_EMAIL
      defaultProject: $GCP_PROJECT_ID
      tokenUri: https://oauth2.googleapis.com/token
    secureJsonData:
      privateKey: $GCP_PRIVATE_KEY
    editable: false 